name: Semgrep
on: [push]
jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'juice-shop/juice-shop'
      - run: semgrep scan --sarif --output=semgrep.sarif --config=auto --include=*.js
      - uses: actions/upload-artifact@v2
        with:
          name: semgrep-report
          path: semgrep.sarif
  send_report:
    if: ${{ always() }}
    needs: semgrep
    name: Send-Report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v2
        with:
          name: semgrep-report
      - name: Upload SARIF file for GitHub Advanced Security Dashboard
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: semgrep.sarif
