name: Semgrep
on: [push]
jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'juice-shop/juice-shop'
      - run: semgrep scan --sarif --output=semgrep.sarif --config=auto --include=*.js
      - run: echo "SEMGREP_SARIF=$(base64 < semgrep.sarif | tr -d '\n')" >> $GITHUB_ENV
  send_report:
    if: ${{ always() }}
    needs: semgrep
    name: Send-Report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: base64 -d << "${{ env.SEMGREP_SARIF }}" > semgrep.sarif
      - name: Upload SARIF file for GitHub Advanced Security Dashboard
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: semgrep.sarif
        if: always()
